-- select a database to start execution.
USE ecommerce;

-- sample look of our data.
SELECT * FROM mytable LIMIT 10;

-- segment_customer is all null in limit of 10 lets check .
SELECT segment_customer FROM mytable where  not null  LIMIT 10; 


-- all of segment_customer are null so we remove that column.
ALTER TABLE mytable
DROP COLUMN segment_customer;

-- to verify the changes work or not .
SHOW COLUMNS FROM mytable;


-- What is the total revenue generated by each customer segment?
SELECT customer_segment,
       ROUND(SUM(total_sales),2) AS total_revenue
FROM mytable
GROUP BY customer_segment
ORDER BY total_revenue DESC;


-- Which customers generated more profit than the average profit?
SELECT customer_name,
       ROUND(SUM(profit),2) AS total_profit
FROM mytable
GROUP BY customer_name
HAVING total_profit > (SELECT AVG(profit) FROM mytable)
ORDER BY total_profit DESC;


-- Which are the top 5 products with the highest total sales?
SELECT product_name,
       ROUND(SUM(total_sales),2) AS sales
FROM mytable
GROUP BY product_name
ORDER BY sales DESC
LIMIT 5;

-- OR

SELECT *
FROM (
    SELECT product_name,
           ROUND(SUM(total_sales),2) AS sales,
           DENSE_RANK() OVER(ORDER BY SUM(total_sales) DESC) AS rnk
    FROM mytable
    GROUP BY product_name
) t
WHERE rnk <= 5;


-- Compare the average sales across product categories.
SELECT product_category,
       ROUND(AVG(total_sales),2) AS avg_sales
FROM mytable
GROUP BY product_category
ORDER BY avg_sales DESC;


-- Which payment methods generated the highest revenue?
SELECT payment_method,
       ROUND(SUM(total_sales),2) AS revenue
FROM mytable
GROUP BY payment_method
ORDER BY revenue DESC;


-- Which countries generated the highest total profit?
SELECT country,
       ROUND(SUM(profit),2) AS total_profit
FROM mytable
GROUP BY country
ORDER BY total_profit DESC;


-- Which regions have the highest average shipping cost?
SELECT region,
       ROUND(AVG(shipping_cost),2) AS avg_shipping_cost
FROM mytable
GROUP BY region
ORDER BY avg_shipping_cost DESC;


-- Which 5 products have the highest average discount percentage?
SELECT product_name,
       ROUND(AVG(discount_percent),2) AS avg_discount
FROM mytable
GROUP BY product_name
ORDER BY avg_discount DESC
LIMIT 5;


-- Classify orders based on discount percentage.
ALTER TABLE mytable
ADD discount_category VARCHAR(30);

UPDATE mytable
SET discount_category =
(CASE
    WHEN discount_percent = 0 THEN 'No Discount'
    WHEN discount_percent <= 10 THEN 'Low Discount'
    WHEN discount_percent <= 25 THEN 'Medium Discount'
    ELSE 'High Discount'
END);


-- What are the top 3 best-selling products within each category?
SELECT product_category,
       product_name,
       sales,
       rnk
FROM
(
    SELECT product_category,
           product_name,
           SUM(quantity) AS sales,
           ROW_NUMBER() OVER(
               PARTITION BY product_category
               ORDER BY SUM(quantity) DESC
           ) AS rnk
    FROM mytable
    GROUP BY product_category, product_name
) t
WHERE rnk <= 3;


-- Which customer segment contributes the highest profit?
SELECT customer_segment,
       ROUND(SUM(profit),2) AS total_profit
FROM mytable
GROUP BY customer_segment
ORDER BY total_profit DESC;


-- Which orders received a discount but still had above-average sales?
SELECT order_id,
       customer_name,
       total_sales,
       discount_percent
FROM mytable
WHERE discount_percent > 0
AND total_sales > (SELECT AVG(total_sales) FROM mytable)
ORDER BY total_sales DESC;


-- What is the revenue contribution of each product category?
SELECT product_category,
       ROUND(SUM(total_sales),2) AS revenue
FROM mytable
GROUP BY product_category
ORDER BY revenue DESC;


-- Find the top 5 customers by total purchase value.
SELECT customer_name,
       ROUND(SUM(total_sales),2) AS total_purchase
FROM mytable
GROUP BY customer_name
ORDER BY total_purchase DESC
LIMIT 5;


-- Compare revenue, profit, and average order value by region.
SELECT region,
       ROUND(SUM(total_sales),2) AS total_revenue,
       ROUND(SUM(profit),2) AS total_profit,
       ROUND(AVG(total_sales),2) AS avg_order_value
FROM mytable
GROUP BY region
ORDER BY total_revenue DESC;
